/**
 * Whole-surface RLS matrix.
 *
 * Tables, write-blocked set, and RPC names are imported from
 * `rls-policy-map.generated.ts` — generated by `bun run rls:generate` from
 * `pg_policies` + `pg_proc`. CI guards drift via `bun run rls:verify`.
 */
import { beforeAll, describe, expect, it } from "vitest";
import { anonClient, operatorClient, requireEnv } from "./helpers";
import {
  ADMIN_RPCS,
  ALL_TABLES,
  CLIENT_WRITE_BLOCKED,
  OPERATOR_RPCS,
} from "./rls-policy-map.generated";

beforeAll(() => requireEnv());

const TABLES = ALL_TABLES;

describe("RLS matrix — anon is blocked everywhere", () => {
  for (const t of TABLES) {
    it(`anon cannot read ${t}`, async () => {
      const c = anonClient();
      const { data, error } = await c.from(t as never).select("*").limit(1);
      expect(error !== null || (data ?? []).length === 0).toBe(true);
    });

    it(`anon cannot insert into ${t}`, async () => {
      const c = anonClient();
      const { error } = await c.from(t as never).insert({} as never);
      expect(error).not.toBeNull();
    });
  }
});

describe("RLS matrix — operator JWT can read every operator table", () => {
  for (const t of TABLES) {
    it(`operator can read ${t}`, async () => {
      const { client } = await operatorClient();
      const { error } = await client.from(t as never).select("*").limit(1);
      // role_change_audit is admin-only — bootstrap operator also gets admin, so should still pass.
      expect(error).toBeNull();
    });
  }
});

describe("RLS matrix — direct client writes blocked on managed tables", () => {
  for (const t of CLIENT_WRITE_BLOCKED) {
    it(`operator cannot directly insert into ${t}`, async () => {
      const { client } = await operatorClient();
      const { error } = await client.from(t as never).insert({} as never);
      expect(error).not.toBeNull();
    });
  }
});

/**
 * Privileged RPC matrix.
 * Each function self-checks role and must reject anon. Operator is the bootstrap user
 * (granted both operator + admin), so admin-gated RPCs succeed; we only assert they
 * do not throw a permission error.
 */
const ADMIN_RPCS = ["grant_user_role", "revoke_user_role", "list_users_with_roles"] as const;
const OPERATOR_RPCS = ["purge_expired_rows", "purge_all_rows", "retention_stats"] as const;

describe("RPC matrix — anon cannot call privileged RPCs", () => {
  for (const fn of [...ADMIN_RPCS, ...OPERATOR_RPCS]) {
    it(`anon rejected from ${fn}`, async () => {
      const c = anonClient();
      const { error } = await c.rpc(fn as never, {} as never);
      // Either RPC denies execute, or function raises 'not authorized'.
      expect(error).not.toBeNull();
    });
  }
});

describe("RPC matrix — operator can introspect retention_stats", () => {
  it("retention_stats returns rows for operator", async () => {
    const { client } = await operatorClient();
    const { data, error } = await client.rpc("retention_stats");
    expect(error).toBeNull();
    expect(Array.isArray(data)).toBe(true);
  });
});
