/**
 * Whole-surface RLS matrix.
 *
 * Tables, write-blocked set, and RPC names are imported from
 * `rls-policy-map.generated.ts` — generated by `bun run rls:generate` from
 * `pg_policies` + `pg_proc`. CI guards drift via `bun run rls:verify`.
 */
import { beforeAll, describe, expect, it } from "vitest";
import { anonClient, operatorClient, requireEnv } from "./helpers";
import {
  ADMIN_RPCS,
  ALL_TABLES,
  CLIENT_WRITE_BLOCKED,
  OPERATOR_RPCS,
} from "./rls-policy-map.generated";
import { INSERT_FIXTURES, isRlsDenial } from "./rls-fixtures";

beforeAll(() => requireEnv());

const TABLES = ALL_TABLES;

// Sanity: every table in the generated map must have a fixture, otherwise
// the insert tests below would silently fall back to {} and might pass for
// the wrong reason (NOT NULL violation instead of RLS).
describe("RLS matrix — fixture coverage", () => {
  it("every table has a realistic insert fixture", () => {
    const missing = TABLES.filter((t) => !INSERT_FIXTURES[t]);
    expect(missing, `add fixtures in e2e/rls-fixtures.ts for: ${missing.join(", ")}`).toEqual([]);
  });
});

describe("RLS matrix — anon is blocked everywhere", () => {
  for (const t of TABLES) {
    it(`anon cannot read ${t}`, async () => {
      const c = anonClient();
      const { data, error } = await c.from(t as never).select("*").limit(1);
      expect(error !== null || (data ?? []).length === 0).toBe(true);
    });

    it(`anon insert ${t} → rejected by RLS (not constraint)`, async () => {
      const c = anonClient();
      const { error } = await c.from(t as never).insert(INSERT_FIXTURES[t] as never);
      expect(error, "insert with realistic payload should still error").not.toBeNull();
      expect(
        isRlsDenial(error),
        `expected RLS denial, got ${error?.code}: ${error?.message}`,
      ).toBe(true);
    });
  }
});

describe("RLS matrix — operator JWT can read every operator table", () => {
  for (const t of TABLES) {
    it(`operator can read ${t}`, async () => {
      const { client } = await operatorClient();
      const { error } = await client.from(t as never).select("*").limit(1);
      // role_change_audit is admin-only — bootstrap operator also gets admin, so should still pass.
      expect(error).toBeNull();
    });
  }
});

describe("RLS matrix — direct client writes blocked on managed tables", () => {
  for (const t of CLIENT_WRITE_BLOCKED) {
    it(`operator insert ${t} → rejected by RLS (not constraint)`, async () => {
      const { client } = await operatorClient();
      const fixture = INSERT_FIXTURES[t] ?? {};
      const { error } = await client.from(t as never).insert(fixture as never);
      expect(error).not.toBeNull();
      expect(
        isRlsDenial(error),
        `expected RLS denial on ${t}, got ${error?.code}: ${error?.message}`,
      ).toBe(true);
    });
  }
});

/**
 * Privileged RPC matrix.
 * Each function self-checks role and must reject anon. Operator is the bootstrap user
 * (granted both operator + admin), so admin-gated RPCs succeed; we only assert they
 * do not throw a permission error. RPC names come from the generated map.
 */

describe("RPC matrix — anon cannot call privileged RPCs", () => {
  for (const fn of [...ADMIN_RPCS, ...OPERATOR_RPCS]) {
    it(`anon rejected from ${fn}`, async () => {
      const c = anonClient();
      const { error } = await c.rpc(fn as never, {} as never);
      // Either RPC denies execute, or function raises 'not authorized'.
      expect(error).not.toBeNull();
    });
  }
});

describe("RPC matrix — operator can introspect retention_stats", () => {
  it("retention_stats returns rows for operator", async () => {
    const { client } = await operatorClient();
    const { data, error } = await client.rpc("retention_stats");
    expect(error).toBeNull();
    expect(Array.isArray(data)).toBe(true);
  });
});
