#!/usr/bin/env bun
/**
 * Generate docs/legal/sub-processor-list.md from docs/sovereignty.md §5.
 *
 * Source of truth: the sub-processor table under `## 5. Sub-processors` in
 * docs/sovereignty.md. This script extracts that table and emits a standalone
 * markdown file customers/procurement teams can be pointed at directly.
 *
 * Usage:
 *   bun run scripts/generate-subprocessor-list.ts          # write file
 *   bun run scripts/generate-subprocessor-list.ts --check  # CI mode: exit 1 if drift
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";

const SOURCE = "docs/sovereignty.md";
const TARGET = "docs/legal/sub-processor-list.md";
const SECTION_HEADING = "## 5. Sub-processors";

type Row = { name: string; purpose: string; region: string; dataClass: string };

function extractSection(md: string): string {
  const start = md.indexOf(SECTION_HEADING);
  if (start === -1) throw new Error(`Cannot find "${SECTION_HEADING}" in ${SOURCE}`);
  const after = md.slice(start + SECTION_HEADING.length);
  const nextHeading = after.search(/\n##?\s|\n---\s*\n/);
  return nextHeading === -1 ? after : after.slice(0, nextHeading);
}

function parseTable(section: string): Row[] {
  const lines = section.split("\n").filter((l) => l.trim().startsWith("|"));
  if (lines.length < 3) throw new Error("Sub-processor table not found or malformed");
  // Drop header + separator rows
  const dataRows = lines.slice(2);
  return dataRows.map((line) => {
    const cells = line.split("|").slice(1, -1).map((c) => c.trim());
    if (cells.length < 4) throw new Error(`Row missing columns: ${line}`);
    const [name, purpose, region, dataClass] = cells;
    return { name, purpose, region, dataClass };
  });
}

function render(rows: Row[], sourceHash: string): string {
  const today = new Date().toISOString().slice(0, 10);
  const tableHeader = "| Sub-processor | Purpose | Region | Data class |\n|---|---|---|---|";
  const tableBody = rows
    .map((r) => `| ${r.name} | ${r.purpose} | ${r.region} | ${r.dataClass} |`)
    .join("\n");
  return `# Sub-processor list

<!-- AUTOGENERATED FROM docs/sovereignty.md §5 — DO NOT EDIT BY HAND -->
<!-- Run: bun run scripts/generate-subprocessor-list.ts -->
<!-- source-sha256: ${sourceHash} -->

_Last generated: ${today}_

This list enumerates every external service that processes AWIP Core operator
data. It is generated from [\`docs/sovereignty.md\`](../sovereignty.md) §5,
which remains the source of truth.

Any new external service added to the codebase **must** update the sovereignty
document in the same change; this file is then regenerated.

${tableHeader}
${tableBody}

## How this list is maintained

1. A sub-processor is added/removed in [\`docs/sovereignty.md\`](../sovereignty.md) §5.
2. \`bun run scripts/generate-subprocessor-list.ts\` regenerates this file.
3. CI (\`.github/workflows/doc-drift.yml\`) re-runs the generator with \`--check\`
   and fails the build if this file is stale.

## Related

- [Data sovereignty](../sovereignty.md) — full posture, egress, and tier roadmap
- [Security](../security.md) — RLS, auth, audit streams
- [Legal templates](./README.md) — DPA + region attestation (planned)
`;
}

function sha256(s: string): string {
  return createHash("sha256").update(s).digest("hex").slice(0, 16);
}

function main() {
  const checkMode = process.argv.includes("--check");
  const md = readFileSync(SOURCE, "utf8");
  const section = extractSection(md);
  const rows = parseTable(section);
  if (rows.length === 0) throw new Error("No sub-processor rows parsed");
  const sourceHash = sha256(section);
  const generated = render(rows, sourceHash);

  if (checkMode) {
    if (!existsSync(TARGET)) {
      console.error(`✗ ${TARGET} does not exist. Run the generator.`);
      process.exit(1);
    }
    const current = readFileSync(TARGET, "utf8");
    // Compare ignoring the "Last generated" date line
    const norm = (s: string) => s.replace(/_Last generated: \d{4}-\d{2}-\d{2}_/, "");
    if (norm(current).trim() !== norm(generated).trim()) {
      console.error(
        `✗ ${TARGET} is out of sync with ${SOURCE} §5.\n` +
          `  Run: bun run scripts/generate-subprocessor-list.ts`,
      );
      process.exit(1);
    }
    console.log(`✓ ${TARGET} is in sync with ${SOURCE} §5 (${rows.length} rows)`);
    return;
  }

  writeFileSync(TARGET, generated);
  console.log(`✓ Wrote ${TARGET} (${rows.length} sub-processors, source sha ${sourceHash})`);
}

main();
