#!/usr/bin/env bun
/**
 * Generate docs/migration-index.md — a chronological table of every migration.
 *
 * For each .sql file in supabase/migrations/, parse the first top-of-file
 * `-- comment` line as the human summary. Files without one show `(no summary)`.
 *
 * Run:  bun run scripts/index-migrations.ts
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const MIG_DIR = "supabase/migrations";
const OUT = "docs/migration-index.md";

type Row = { file: string; ts: string; summary: string };

function parseSummary(content: string): string {
  for (const line of content.split("\n", 20)) {
    const t = line.trim();
    if (!t) continue;
    if (t.startsWith("-- ")) return t.slice(3).trim();
    // first non-comment, non-blank line → no summary
    if (!t.startsWith("--")) return "(no summary)";
  }
  return "(no summary)";
}

function tsFromName(name: string): string {
  const m = name.match(/^(\d{8})(\d{6})/);
  if (!m) return "????-??-?? ??:??:??";
  const [, d, t] = m;
  return `${d.slice(0, 4)}-${d.slice(4, 6)}-${d.slice(6, 8)} ${t.slice(0, 2)}:${t.slice(2, 4)}:${t.slice(4, 6)}`;
}

const rows: Row[] = readdirSync(MIG_DIR)
  .filter((f) => f.endsWith(".sql"))
  .sort()
  .map((file) => {
    const content = readFileSync(join(MIG_DIR, file), "utf8");
    return { file, ts: tsFromName(file), summary: parseSummary(content) };
  });

const withSummary = rows.filter((r) => r.summary !== "(no summary)").length;

const md = [
  "# Migration index",
  "",
  `_Auto-generated by \`scripts/index-migrations.ts\`. Do not edit by hand._`,
  "",
  `**${rows.length}** migrations · **${withSummary}** documented · **${rows.length - withSummary}** missing top-of-file summary.`,
  "",
  "Add a `-- one-line summary` to the top of any unsummarised migration when you touch it. See [`docs/migrations.md`](./migrations.md).",
  "",
  "| When (UTC) | File | Summary |",
  "|---|---|---|",
  ...rows.map((r) => `| ${r.ts} | \`${r.file}\` | ${r.summary} |`),
  "",
].join("\n");

writeFileSync(OUT, md);
console.log(`Wrote ${OUT}: ${rows.length} migrations (${withSummary} documented)`);
