#!/usr/bin/env bun
/**
 * scripts/new-module.ts
 *
 * Scaffolds a new module so it stops appearing as `module_silent_24h`:
 *   1. Writes a typed input contract under supabase/functions/_shared/contracts/<slug>.ts
 *   2. Prints a `register-module` curl snippet + a `module_heartbeat` capability_events snippet
 *
 * Usage:
 *   bun run scripts/new-module.ts <module-slug> <capability-id> [--dry-run]
 *
 * Idempotent: existing contract file is left untouched.
 */
import { mkdir, writeFile, access } from "node:fs/promises";
import { dirname } from "node:path";

const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const [slug, capability] = args.filter((a) => !a.startsWith("--"));

if (!slug || !capability) {
  console.error("Usage: bun run scripts/new-module.ts <module-slug> <capability-id> [--dry-run]");
  process.exit(1);
}

if (!/^[a-z][a-z0-9_]*$/.test(slug)) {
  console.error(`slug "${slug}" must be snake_case (lower-case letters, digits, underscore).`);
  process.exit(1);
}

const contractPath = `supabase/functions/_shared/contracts/${slug}.ts`;
const contractBody = `// Auto-generated by scripts/new-module.ts — refine fields before first deploy.
// See docs/agents/contract-checklist.md.

export interface ${toPascal(slug)}Input {
  /** Idempotency key — required for any write path. */
  idempotency_key: string;
  /** Tenant context. Resolver will use resolve_entity_logged() against this. */
  tenant_id: string;
  /** Free-form payload — replace with explicit fields before exposing. */
  payload: Record<string, unknown>;
}

export function is${toPascal(slug)}Input(x: unknown): x is ${toPascal(slug)}Input {
  if (!x || typeof x !== "object") return false;
  const o = x as Record<string, unknown>;
  return typeof o.idempotency_key === "string"
    && typeof o.tenant_id === "string"
    && typeof o.payload === "object" && o.payload !== null;
}
`;

const curlRegister = `curl -X POST "$SUPABASE_URL/functions/v1/awip-api/capabilities/register" \\
  -H "x-awip-service-token: $AWIP_SERVICE_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{"id":"${capability}","name":"${capability.replace(/_/g, " ")}","owning_module":"${slug}","version":"0.1.0","status":"proposed"}'`;

const heartbeatSql = `INSERT INTO public.capability_events (capability_id, event_type, payload, actor)
VALUES ('${capability}', 'module_heartbeat', '{"source":"new-module.ts"}'::jsonb, 'operator');`;

async function exists(p: string): Promise<boolean> {
  try { await access(p); return true; } catch { return false; }
}

async function main() {
  console.log(`new-module scaffold: slug="${slug}" capability="${capability}" dryRun=${dryRun}`);

  if (await exists(contractPath)) {
    console.log(`✓ contract already present: ${contractPath} (left untouched)`);
  } else if (dryRun) {
    console.log(`[dry-run] would write contract: ${contractPath}`);
  } else {
    await mkdir(dirname(contractPath), { recursive: true });
    await writeFile(contractPath, contractBody, "utf8");
    console.log(`✓ wrote ${contractPath}`);
  }

  console.log("\n-- 1. Register the capability (one-shot) --");
  console.log(curlRegister);
  console.log("\n-- 2. Send first heartbeat (run via supabase--insert or the awip-api) --");
  console.log(heartbeatSql);
  console.log("\n-- 3. Add a regular heartbeat path in your module's cron / health pulse. --");
}

function toPascal(s: string): string {
  return s.split("_").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("");
}

main().catch((e) => { console.error(e); process.exit(1); });
